# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QObject, pyqtSlot
from WidgetParams import WidgetParams


class MainWindow(QtWidgets.QWidget):
    def __init__(self):
        QtWidgets.QWidget.__init__(self)
        self.setObjectName("MainWindow")
        self.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(40, 30, 201, 50))
        self.pushButton.setObjectName("pushButton")
        self.pushButtonImg = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonImg.setGeometry(QtCore.QRect(300, 30, 201, 50))
        self.pushButtonImg.setObjectName("pushButtonImg")
        self.pushButtonTxt = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonTxt.setGeometry(QtCore.QRect(560, 30, 201, 50))
        self.pushButtonTxt.setObjectName("pushButtonTxt")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(50, 80, 600, 100))
        self.widget.setObjectName("widget")
        self.widget1 = QtWidgets.QWidget(self.widget)
        self.widget1.setGeometry(QtCore.QRect(20, 10, 500, 100))
        self.widget1.setObjectName("widget1")
        self.gridLayout = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget1)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 1, 0, 1, 1)

        self.widget2 = QtWidgets.QWidget(self.widget)
        self.widget2.setGeometry(QtCore.QRect(20, 10, 500, 100))
        self.widget2.setObjectName("widget2")
        self.gridLayout2 = QtWidgets.QGridLayout(self.widget2)
        self.gridLayout2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout2.setObjectName("gridLayout2")
        self.horizontalLayout2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout2.setObjectName("horizontalLayout2")
        self.label2 = QtWidgets.QLabel(self.widget2)
        self.label2.setObjectName("label2")
        self.horizontalLayout2.addWidget(self.label2)
        self.lineEdit2 = QtWidgets.QLineEdit(self.widget2)
        self.lineEdit2.setObjectName("lineEdit2")
        self.horizontalLayout2.addWidget(self.lineEdit2)
        self.pushButton_22 = QtWidgets.QPushButton(self.widget2)
        self.pushButton_22.setObjectName("pushButton_22")
        self.horizontalLayout2.addWidget(self.pushButton_22)
        self.gridLayout2.addLayout(self.horizontalLayout2, 0, 0, 1, 1)
        self.pushButton_32 = QtWidgets.QPushButton(self.widget2)
        self.pushButton_32.setObjectName("pushButton_32")
        self.gridLayout2.addWidget(self.pushButton_32, 1, 0, 1, 1)

        # self.widgetParams = WidgetParams(self.centralwidget, 70, 260)

        self.setWindowTitle("MainWindow")
        self.pushButton.setText("Преобразовать PDF")
        self.pushButtonImg.setText("Перераспознать страницу")
        self.pushButtonTxt.setText("Объединить .csv-файлы")
        self.label.setText("Введите путь к PDF-файлам")
        self.pushButton_2.setText("Обзор")
        self.pushButton_3.setText("Преобразовать")
        self.label2.setText("Введите путь к изображению")
        self.pushButton_22.setText("Обзор")
        self.pushButton_32.setText("Перераспознать")
        self.pushButton_2.clicked.connect(self.browseSlot)
        self.pushButton_22.clicked.connect(self.browseImgSlot)
        self.lineEdit.returnPressed.connect(self.returnPressedSlot)
        self.lineEdit2.returnPressed.connect(self.returnPressedImgSlot)
        self.pushButton.clicked.connect(self.seeWidgetSlot)
        self.pushButtonImg.clicked.connect(self.seeWidgetImgSlot)
        self.pushButtonTxt.clicked.connect(self.UniteCsvSlot)

        self.pushButton_3.clicked.connect(self.startRecSlot)
        self.pushButton_32.clicked.connect(self.startImgSlot)

        QtCore.QMetaObject.connectSlotsByName(self)

    @pyqtSlot()
    def returnPressedSlot(self):
        pass

    @pyqtSlot()
    def returnPressedImgSlot(self):
        pass

    @pyqtSlot()
    def browseSlot(self):
        pass

    @pyqtSlot()
    def browseImgSlot(self):
        pass

    @pyqtSlot()
    def seeWidgetSlot(self):
        pass

    @pyqtSlot()
    def seeWidgetImgSlot(self):
        pass

    @pyqtSlot()
    def UniteCsvSlot(self):
        pass

    @pyqtSlot()
    def startRecSlot(self):
        pass

    @pyqtSlot()
    def startImgSlot(self):
        pass


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = MainWindow()
    MainWindow.show()
    sys.exit(app.exec_())
